name: Build and upload binaries to release

on:
  push:
#  create:
#    tags:
#    - h*

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: tasky-api
            asset_name: tasky-api-linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: .
      - name: Build project
        uses: actions-rs/cargo@v1
        env:
          TWO_CAPTCHA_API_KEY: ${{ secrets.TWO_CAPTCHA_API_KEY }}
        with:
          command: build
#          args: --release --all-features
      - name: Run binary
        env:
          TWO_CAPTCHA_API_KEY: ${{ secrets.TWO_CAPTCHA_API_KEY }}
#        run: RUST_LOG=debug ./target/release/discord-bomber --accounts 10 --invite_link PEd4HWYs
        run: RUST_LOG=debug ./target/debug/discord-bomber --accounts 10 --invite_link PEd4HWYs